// Declaración de variables
int pBuzzer = 2;
int entero = 1000/2;
int medio = 1000/4;
int tercio = 1000/6;
int cuarto = 1000/8;
int octavo = 1000/16;
double pausa = 1.30;

// Notas
int Do = 262;
int Re = 294;
int Mi = 330;
int Fa = 349;
int Sol = 392;
int La = 440;
int Si = 493;
int Do1 = 523;
int Re1 = 587;
int Mi1 = 659;
int Fa1 = 699;
int Sol1 = 784;
void setup() {
  pinMode(pBuzzer, OUTPUT);

}

void loop() {
 //Melodía
 tone(pBuzzer, Sol, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Sol, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Sol, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Do, 2*entero);
 delay(2*entero*pausa);
 tone(pBuzzer, Sol, 2*entero);
 delay(2*entero*pausa);
 tone(pBuzzer, Fa, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Mi, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Re, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Do1, 2*entero);
 delay(2*entero*pausa);
 tone(pBuzzer, Sol, entero);
 delay(entero*pausa);
  tone(pBuzzer, Fa, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Mi, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Re, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Do1, 2*entero);
 delay(2*entero*pausa);
 tone(pBuzzer, Sol, entero);
 delay(entero*pausa);
 tone(pBuzzer, Fa, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Mi, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Fa, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Re, 2*entero);
 delay(2*entero*pausa);
 tone(pBuzzer, Sol, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Sol, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Sol, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Sol, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Sol, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Sol, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Do, 2*entero);
 delay(2*entero*pausa);
 tone(pBuzzer, Sol, 2*entero);
 delay(2*entero*pausa);
 tone(pBuzzer, Fa, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Mi, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Re, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Do1, 2*entero);
 delay(2*entero*pausa);
 tone(pBuzzer, Sol, entero);
 delay(entero*pausa);
 tone(pBuzzer, Fa, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Mi, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Re, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Do1, 2*entero);
 delay(2*entero*pausa);
 tone(pBuzzer, Sol, entero);
 delay(entero*pausa);
 tone(pBuzzer, Fa, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Mi, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Re, tercio);
 delay(tercio*pausa);
 tone(pBuzzer,Sol, entero);
 delay(entero*pausa);
 tone(pBuzzer,La, 2*entero);
 delay(2*entero*pausa);
 tone(pBuzzer,Fa, cuarto);
 delay(cuarto*pausa);
 tone(pBuzzer, Mi, cuarto);
 delay(cuarto*pausa);
 tone(pBuzzer,Re, cuarto);
 delay(cuarto*pausa);
 tone(pBuzzer,Do, cuarto);
 delay(cuarto*pausa);
 tone(pBuzzer,Do, tercio);
 delay(tercio*pausa);
 tone(pBuzzer,Re, tercio);
 delay(tercio*pausa);
 tone(pBuzzer,Mi, tercio);
 delay(tercio*pausa);
 tone(pBuzzer,Re, medio);
 delay(medio*pausa);
 tone(pBuzzer,La, medio);
 delay(medio*pausa);
 tone(pBuzzer, Si, entero);
 delay(entero*pausa);
 tone(pBuzzer,Sol, entero);
 delay(entero*pausa);
 tone(pBuzzer,La, 2*entero);
 delay(2*entero*pausa);
  tone(pBuzzer,Fa, cuarto);
 delay(cuarto*pausa);
 tone(pBuzzer, Mi, cuarto);
 delay(cuarto*pausa);
 tone(pBuzzer,Re, cuarto);
 delay(cuarto*pausa);
 tone(pBuzzer,Do, cuarto);
 delay(cuarto*pausa);
 tone(pBuzzer, Sol, entero);
 delay(entero*pausa);
 tone(pBuzzer, Re, 2*entero);
 delay(2*entero*pausa);
 tone(pBuzzer, Sol, entero);
 delay(entero*pausa);
 tone(pBuzzer, La, 2*entero);
 delay(2*entero*pausa);
 tone(pBuzzer,Fa, cuarto);
 delay(cuarto*pausa);
 tone(pBuzzer, Mi, cuarto);
 delay(cuarto*pausa);
 tone(pBuzzer,Re, cuarto);
 delay(cuarto*pausa);
 tone(pBuzzer,Do, cuarto);
 delay(cuarto*pausa);
 tone(pBuzzer,Do, tercio);
 delay(tercio*pausa);
 tone(pBuzzer,Re, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Mi, tercio);
 delay(tercio*pausa);
 tone(pBuzzer,Re, medio);
 delay(medio*pausa);
 tone(pBuzzer,La, medio);
 delay(medio*pausa);
 tone(pBuzzer,Si, entero);
 delay(entero*pausa);
 tone(pBuzzer,Sol, entero);
 delay(entero*pausa);
 tone(pBuzzer,Do1, medio);
 delay(medio*pausa);
 delay(2*entero);
 delay(2*entero*pausa);
 delay(4*entero);
 delay(4*entero*pausa);
 delay(3*entero);
 delay(3*entero*pausa);
 tone(pBuzzer, Sol, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Sol, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Sol, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Do, 2*entero);
 delay(2*entero*pausa);
 tone(pBuzzer,Sol, 2*entero);
 delay(2*entero*pausa);
 tone(pBuzzer, Fa, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Mi, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Re, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Do, medio);
 delay(medio*pausa);
 tone(pBuzzer, Sol, entero);
 delay(entero*pausa);
 tone(pBuzzer, Fa, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Mi, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Re, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Do, medio);
 delay(medio*pausa);
 tone(pBuzzer, Sol, entero);
 delay(entero*pausa);
 tone(pBuzzer, Fa, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Mi, tercio);
 delay(tercio*pausa);
 tone(pBuzzer, Re, tercio);
 delay(tercio*pausa);
 
 
 
 

 

}
